#========================================
#           站点功能【必需】
#       请不要更改前面的关键字
# ========================================


#========================================
# 涉及 avatar favicon bg 之类的图片参数
# 参照下例
# 外链形式（推荐）
# avatar: https://xxx.jpg
# 站内相对链接，需要提前将图片
# 放入source/images文件夹下
# avatar: /images/yyy.png 
#========================================

#========================================
# 涉及color 之类的设置
# 参照下例，支持 hex、rgb、rgba、hsl、hsla
# 需要引号引起来
# c-1: '#B28FCE'
# c-2: 'rgb(233, 224, 207)'
#========================================

# 主标题、副标题、作者、头像、网站图标
title: 椎咲良田
subtitle: 
author: 椎咲良田
avatar: https://i.loli.net/2019/02/24/5c71bf051a8f2.jpg
favicon: https://i.loli.net/2019/02/24/5c71bf051a8f2.jpg

# 页面可删除或新建
# 但是icon只有那么几个(fontello.styl)
menu:
  home:
    name: 首页
    url: /
    icon: icon-home
  archives:
    name: 归档
    url: /archives
    icon: icon-archives
  categories:
    name: 分类
    url: /categories
    icon: icon-categories
  tags:
    name: 标签
    url: /tags
    icon: icon-tags
  friends:
    name: 友链
    url: /friends
    icon: icon-friends
  about:
    name: 关于
    url: /about
    icon: icon-about

# 配置页面的quote, 其中首页和归档页不需要配置
quotes:
  enable: true
  categories:
    enable: true
    quote: 行云流水，落笔生花
  tags:
    enable: true
    quote: 列卒周匝，星罗云布
  friends:
    enable: true
    quote: 青青子衿，悠悠我心
  about:
    enable: true
    quote: 蝉鸣如雨，花宵道中

# 底部的信息设置 
# since 为起始年，可选
# (sub)title，可选
footer:
  enable: true
  title: 椎咲良田
  subtitle: 昨日、今日、明日

# 背景图片 
background:
  enable: true
  imageUrl: https://i.loli.net/2019/02/24/5c71bf05ea594.jpg

# 回到顶部挂件
backToTop:
  enable: true
# 顶部进度条
progressBar: 
  enable: true

# 点击页面的烟火效果
fireworks:
  enable: true


# 图文模式 建议默认背景颜色是默认图片的主色
postCoverImage: 
  enable: true
  defaultImage: https://i.loli.net/2019/02/24/5c71bf0534682.jpg
  defaultBgColor: rgba(233, 224, 207, 0.66)

# 浏览次数(热度)
# https://leancloud.cn 注册后得到 AppID and AppKey.
leancloud:
  enable: true
  app_id: zsXIwfsAOXq9j5T8aI8TSeXg-gzGzoHsz
  app_key: jF8GAJU2aJdgB6qQC9XGtwJw

# 加载音乐插件 
APlayer:
  enable: true
  list: [
    {
      name: Once more,
      artist: 阿保剛,
      url: https://files.catbox.moe/13boxb.mp3,
      cover: https://i.loli.net/2019/04/18/5cb87157c617e.jpg
    },
    {
      name: All or None,
      artist: 阿保剛,
      url: https://files.catbox.moe/4x69y9.mp3,
      cover: https://i.loli.net/2019/04/18/5cb87157b537a.jpg
    },
    {
      name: Karma,
      artist: 阿保剛,
      url: https://files.catbox.moe/r5dsuh.mp3,
      cover: https://i.loli.net/2019/04/18/5cb871583cfb7.jpg,
    },
    {
      name: 星の奏でる歌,
      artist: 阿保剛,
      url: https://files.catbox.moe/m1wd57.mp3,
      cover: https://i.loli.net/2019/04/18/5cb871585123b.jpg
    }
  ]

