#========================================
#           站点功能【必需】
# ========================================
title: '蝉时雨'
subtitle: '蝉鸣如雨 花宵道中'
favicon: https://i.loli.net/2019/02/19/5c6b824e6e83e.png

# 只引入了部分字体图标 切勿更换
menu:
  home:
    name: '首页'
    url: /
    icon: 'icon-home'
  archives:
    name: '归档'
    url: /archives
    icon: 'icon-archives'
  categories:
    name: '分类'
    url: /categories
    icon: 'icon-categories'
  tags:
    name: '标签'
    url: /tags
    icon: 'icon-tags'
  moods:
    name: '心情'
    url: /moods
    icon: 'icon-moods'
  friends:
    name: '友链'
    url: /friends
    icon: 'icon-friends'
  about:
    name: '关于'
    url: /about
    icon: 'icon-about'

# 文章顶端大图
post_cover_image: 
  enable: true
  default_image: https://i.loli.net/2019/01/24/5c49bd8dad2f5.jpg

# 底部的信息设置
footer:
  show:
    enable: true
  since:
  title:
  subtitle:

# 背景图片 && 背景变化效果（通过enable设置）
bg_animes:
  default_bg_image: https://i.loli.net/2018/12/16/5c164034ac74c.jpg
  enable: false
  images_num: 10
  images:
    i-1: https://i.loli.net/2018/12/16/5c164034ac74c.jpg
    i-2: https://i.loli.net/2018/12/09/5c0cc108c3b5c.jpg
    i-3: https://i.loli.net/2018/12/09/5c0cc1010f9e5.jpg
    i-4: https://i.loli.net/2018/12/09/5c0cc10d3d771.jpg
    i-5: https://i.loli.net/2018/12/09/5c0cc111f30a3.jpg
    i-6: https://i.loli.net/2018/12/09/5c0cc1159ea42.jpg
    i-7: https://i.loli.net/2018/12/09/5c0cc11b0691b.jpg
    i-8: https://i.loli.net/2018/12/09/5c0cc12115c2e.jpg
    i-9: https://i.loli.net/2018/12/09/5c0cc0f409d63.jpg
    i-10: https://i.loli.net/2018/12/09/5c0cc1268cd42.jpg

# 点击页面的烟火效果
fireworks:
  enable: false

# 回到顶部挂件
backToTop:
  enable: false

# 顶端进度条效果
progressBar: 
  enable: false
  


