#========================================
#           站点功能【必需】
#       请不要更改前面的关键字
# ========================================

#========================================
# 涉及 avatar favicon bg 之类的图片参数
# 参照下例
# 外链形式（推荐）
# avatar: https://xxx.jpg
# 站内相对链接，需要提前将图片
# 放入source/images文件夹下
# avatar: /images/yyy.png
# 涉及color 之类的设置
# 参照下例，支持 hex、rgb、rgba、hsl、hsla
# 需要引号引起来
# c-1: '#B28FCE'
# c-2: 'rgb(233, 224, 207)'
#========================================

# 主标题、副标题、作者、头像、网站图标
title: 椎咲良田
subtitle: "快走吧 趁风停止之前"
author: 椎咲良田
description: "世界并不美丽，却也因此而美丽"
avatar: https://i.loli.net/2019/02/24/5c71bf051a8f2.jpg
favicon: https://i.loli.net/2019/02/24/5c71bf051a8f2.jpg

# 导航栏 
# 如果不需要某个导航，可以将 enable 置为 false 或 删除
# icon只有那么几个 在 fontello.styl 中
menu:
  index:
    enable: true
    name: 首页
    url: /
    icon: icon-index
  archives:
    enable: true
    name: 归档
    url: /archives/
    icon: icon-archives
  categories:
    enable: true
    name: 分类
    url: /categories/
    icon: icon-categories
  tags:
    enable: true
    name: 标签
    url: /tags/
    icon: icon-tags
  books:
    enable: true
    name: 书单
    url: /books/
    icon: icon-books
  inspiration:
    enable: true
    name: 灵感
    url: /inspiration/
    icon: icon-inspiration
  friends:
    enable: true
    name: 友链
    url: /friends/
    icon: icon-friends
  about:
    enable: true
    name: 关于
    url: /about/
    icon: icon-about

# 底部的信息设置 
# since 为起始年，可选
# (sub)title，可选
footer:
  enable: true
  since: 2018
  title: 椎咲良田
  subtitle: "快走吧 趁风停止之前"

# 背景图片 电脑页面 手机页面 文章页面
pcImage: /images/pc.png
spImage: /images/mobile.png
PostImage: /images/postDefaultImage .png

# 回到顶部挂件
backToTop:
  enable: true