#========================================
#           站点功能【必需】
#       请不要更改前面的关键字
# ========================================


#========================================
# 涉及 avatar favicon bg 之类的图片参数
# 参照下例
# 外链形式（推荐）
# avatar: https://xxx.jpg
# 站内相对链接，需要提前将图片
# 放入source/images文件夹下
# avatar: /images/yyy.png 
#========================================

#========================================
# 涉及color 之类的设置
# 参照下例，支持 hex、rgb、rgba、hsl、hsla
# 需要引号引起来
# c-1: '#B28FCE'
# c-2: 'rgb(233, 224, 207)'
#========================================

# 主标题、副标题、作者、头像、网站图标
title: 椎咲良田
subtitle: 
author: 椎咲良田
avatar: https://i.loli.net/2019/02/24/5c71bf051a8f2.jpg
favicon: https://i.loli.net/2019/02/24/5c71bf051a8f2.jpg

# 页面可删除或新建
# 但是icon只有那么几个(fontello.styl)
menu:
  home:
    name: 首页
    url: /
    icon: icon-home
  archives:
    name: 归档
    url: /archives
    icon: icon-archives
  categories:
    name: 分类
    url: /categories
    icon: icon-categories
  tags:
    name: 标签
    url: /tags
    icon: icon-tags
  friends:
    name: 友链
    url: /friends
    icon: icon-friends
  about:
    name: 关于
    url: /about
    icon: icon-about

# 配置页面的quote, 其中首页和归档页不需要配置
quotes:
  enable: true
  categories:
    enable: true
    quote: 行云流水，落笔生花
  tags:
    enable: true
    quote: 列卒周匝，星罗云布
  friends:
    enable: true
    quote: 青青子衿，悠悠我心
  about:
    enable: true
    quote: 蝉鸣如雨，花宵道中

# 底部的信息设置 
# since 为起始年，可选
# (sub)title，可选
footer:
  show:
    enable: true
  since: 
  title: 椎咲良田
  subtitle: 昨日、今日、明日

# 顶部边框颜色和标签颜色设置
# num为颜色数目
# 因为#属于特殊字符， 需要用引号。
themeColors:
  enable: true
  num: 10
  colors:
    c-1: '#B28FCE' # 薄
    c-2: '#86C166' # 苗
    c-3: '#F9BF45' # 玉子
    c-4: '#FAD689' # 浅黄
    c-5: '#F596AA' # 桃
    c-6: '#E79460' # 洗柿
    c-7: '#2EA9DF' # 露草
    c-8: '#FFBA84' # 洒落柿
    c-9: '#7DB9DE' # 勿忘草
    c-10: '#FF99FF' #

# 分类页面每个分类的
# bg、avatar、desc, 可选

categories:
  enable: true
  cates:
    num: 1
    cat-1:
      bg: https://i.loli.net/2019/02/24/5c71bf0544b21.jpg
      avatar: https://i.loli.net/2019/02/24/5c71bf0544b21.jpg
      desc: 

# 图文模式 建议默认背景颜色是默认图片的主色
post_cover_image: 
  enable: true
  default_image: https://i.loli.net/2019/02/24/5c71bf0534682.jpg
  default_bg_color: rgba(233, 224, 207, 0.66)

# 背景图片 
bg_animes:
  enable: true
  default_bg_image: https://i.loli.net/2019/02/24/5c71bf05ea594.jpg

# 点击页面的烟火效果
fireworks:
  enable: true

# 回到顶部挂件
backToTop:
  enable: true

# 顶端进度条效果
progressBar: 
  enable: true

# fancybox 相册功能
fancybox:
  enable: true

# gitalk留言功能
# https://github.com/gitalk/gitalk
gitalk:
  enable: true
  owner: sanshiliuxiao
  repo: comments
  admin: sanshiliu
  clientID: 02a8646fb47500207ba5
  clientSecret: 34329ab4516471939dbfff103e29669b7f7ae515

# 浏览次数(热度)
# https://leancloud.cn 注册后得到 AppID and AppKey.
leancloud:
  enable: true
  app_id: zsXIwfsAOXq9j5T8aI8TSeXg-gzGzoHsz
  app_key: jF8GAJU2aJdgB6qQC9XGtwJw