#========================================
#           站点功能【必需】
# ========================================
title: '蝉时雨'
subtitle: '蝉鸣如雨 花宵道中'
favicon: 'https://i.loli.net/2019/02/19/5c6b824e6e83e.png'

# 只引入了部分字体图标 切勿更换
menu:
  home:
    name: '首页'
    url: /
    icon: 'icon-home'
  archives:
    name: '归档'
    url: /archives
    icon: 'icon-archives'
  categories:
    name: '分类'
    url: /categories
    icon: 'icon-categories'
  tags:
    name: '标签'
    url: /tags
    icon: 'icon-tags'
  moods:
    name: '心情'
    url: /moods
    icon: 'icon-moods'
  books:
    name: '书单'
    url: /books
    icon: 'icon-books'
  friends:
    name: '友链'
    url: /friends
    icon: 'icon-friends'
  about:
    name: '关于'
    url: /about
    icon: 'icon-about'

# 配置页面的quote, 其中首页和归档页不需要配置
quotes:
  enable: true
  categories:
    enable: true
    quote: '行云流水，落笔生花'
  tags:
    enable: true
    quote: '列卒周匝，星罗云布'
  moods:
    enable: true
    quote: '欲言又止，止言又欲'
  books:
    enable: true
    quote: '吾生也有涯，而知也无涯'
  friends:
    enable: true
    quote: '青青子衿，悠悠我心'
  about:
    enable: true
    quote: '蝉鸣如雨，花宵道中'

# 底部的信息设置
footer:
  show:
    enable: true
  since: 
  title:  
  subtitle: 

# themeColors
# 可用于归档的顶部边框颜色设置
themeColors:
  enable: true
  num: 10
  colors:
    c-1: '#B28FCE' # 薄
    c-2: '#86C166' # 苗
    c-3: '#F9BF45' # 玉子
    c-4: '#FAD689' # 浅黄
    c-5: '#F596AA' # 桃
    c-6: '#E79460' # 洗柿
    c-7: '#2EA9DF' # 露草
    c-8: '#FFBA84' # 洒落柿
    c-9: '#7DB9DE' # 勿忘草
    c-10: '#FF99FF'

# 分类页面的bg、avatar、desc说明设置
categories:
  enable: true
  cates:
    num: 2
    cat-1:
      bg: 'https://i.loli.net/2018/12/09/5c0cc2efb6814.jpg'
      avatar: 'https://i.loli.net/2018/12/09/5c0cc2efb6814.jpg'
      desc: '偷偷给你看点东西'
    cat-2:
      bg: 'https://i.loli.net/2018/12/09/5c0cc2eabee8e.jpg'
      avatar: 'https://i.loli.net/2018/12/09/5c0cc2eabee8e.jpg'
      desc:  拾花集


# 图文模式 建议默认背景颜色是默认图片的主色
post_cover_image: 
  enable: true
  default_image: 'https://i.loli.net/2019/01/24/5c49bd8dad2f5.jpg'
  default_bg_color: 'rgba(233, 224, 207,0.66)'

# 背景图片 && 背景变化效果（通过enable设置）
bg_animes:
  default_bg_image: 'https://i.loli.net/2018/12/16/5c164034ac74c.jpg'
  enable: false
  images_num: 10
  images:
    i-1: 'https://i.loli.net/2018/12/16/5c164034ac74c.jpg'
    i-2: 'https://i.loli.net/2018/12/09/5c0cc108c3b5c.jpg'
    i-3: 'https://i.loli.net/2018/12/09/5c0cc1010f9e5.jpg'
    i-4: 'https://i.loli.net/2018/12/09/5c0cc10d3d771.jpg'
    i-5: 'https://i.loli.net/2018/12/09/5c0cc111f30a3.jpg'
    i-6: 'https://i.loli.net/2018/12/09/5c0cc1159ea42.jpg'
    i-7: 'https://i.loli.net/2018/12/09/5c0cc11b0691b.jpg'
    i-8: 'https://i.loli.net/2018/12/09/5c0cc12115c2e.jpg'
    i-9: 'https://i.loli.net/2018/12/09/5c0cc0f409d63.jpg'
    i-10: 'https://i.loli.net/2018/12/09/5c0cc1268cd42.jpg'

# 点击页面的烟火效果
fireworks:
  enable: false

# 回到顶部挂件
backToTop:
  enable: false

# 顶端进度条效果
progressBar: 
  enable: false
  
# gitalk留言功能
gitalk:
  enable: false
  owner: 
  repo: 
  admin: 
  clientID: 
  clientSecret: 

    
    
    
    
    
    
    
    
    
    



